### ISSUE TITLE
可以支持chatglm吗？

### ISSUE THREAD

**Issue by xiaogang-github** [huggingface/optimum#1040]
### Feature request

使onnx支持导出chatglm的模型

### Motivation

我目前在使用chatglm-6b来实现一个本地的智能机器人帮助我管理一些内容，单纯的使用chatglm的时候速度较慢。我看onnx可以为模型推理提速，但是当我使用onnx尝试将chatglm的模型转换为onnx的模型时提示我不支持chatglm。我看历史问题中也没有看到相关的问题，是否可以让onnx支持chatglm

### Your contribution

no

**Comment by JingyaHuang** [comment]
Hi @xiaogang-github, ChatGLM is not yet a native model in Transformers. The best would be to have it in Transformers before extending it to Optimum. There is an issue opened in Transformers, and you could upvote it if interested: https://github.com/huggingface/transformers/issues/22290

Otherwise, Optimum would extend its support for models with remote code. I'll check with my team what would be the best way to support it in Optimum, and will roll back to you later.

**Comment by JingyaHuang** [comment]
Hi @xiaogang-github, some updates on the support of chatglm as well as other models using `trust_remote_code`.

@fxmarty added the support for custom onnx config #1143 which means that you can bring your custom onnx config for Chatglm, and then leverage optimum package with the `custom_onnx_configs` option. 

More guide can be found here: https://huggingface.co/docs/optimum/main/en/exporters/onnx/usage_guides/export_a_model#custom-export-of-transformers-models

In long run, it would make sense to open a PR directly in the hub on the Chatglm checkpoint to store the config so that other user could benefit from it. But for the moment, are you interested in giving it a try?

Feel free to ping me if you do and need help with it.

**Comment by fxmarty** [comment]
Fixed in https://github.com/huggingface/optimum/pull/1166, feel free to refer to https://huggingface.co/docs/optimum/main/en/exporters/onnx/usage_guides/export_a_model#custom-export-of-transformers-models for the usage!
