### ISSUE TITLE
[SAM] Split encoder and mask decoder into separate .onnx files

### ISSUE THREAD

**Issue by xenova** [huggingface/optimum#1078]
### Feature request

Currently, exporting SAM models with optimum results in a single .onnx file (https://huggingface.co/Xenova/sam-vit-base/tree/main/onnx). It would be great if we could add an option to separate the encoder and decoder into separate onnx files (like traditional seq2seq models).

Example SAM exports for which this has been done:
- https://huggingface.co/visheratin/segment-anything-vit-b/tree/main
- https://huggingface.co/visheratin/segment-anything-vit-l/tree/main
- https://huggingface.co/visheratin/segment-anything-vit-h/tree/main

### Motivation

The primary motivation for this feature request is to reuse the encoded image (which should only be computed once), and then use the decoder for querying. At the moment, users would have to encode the image each time they wish to perform a query.

This would be great for Transformers.js.

### Your contribution

I can integrate this into Transformers.js once it's available.

**Comment by xenova** [comment]
Just wanted to bump this issue as we've recently got another feature request for this (https://github.com/xenova/transformers.js/issues/163) and I think this could make for an awesome demo application!
cc @michaelbenayoun @fxmarty

**Comment by fdwr** [comment]
> How are you splitting encoder and decoder? Have you experimented with it to reuse embedding in the decode pass?

(replying to you here since I don't have other contact info) I probably didn't understand your question clearly yesterday through the noise, but we used the encoder/decoder separately, loading [this example](https://github.com/facebookresearch/segment-anything/blob/main/notebooks/onnx_model_example.ipynb) inside VS code to accept a custom image and generate the .onnx model and .npy embedding, followed by running [this demo app](https://github.com/facebookresearch/segment-anything/blob/6fdee8f2727f4506cfbbe553e23b895e27956588/demo/src/App.tsx#L22) with the decoder .onnx file and generated .npy embedding to map mouse coordinates to the mask.

**Comment by xenova** [comment]
Hey! 👋 

> loading [this example](https://github.com/facebookresearch/segment-anything/blob/main/notebooks/onnx_model_example.ipynb) inside VS code to accept a custom image and generate the .onnx model and .npy embedding

Right, so I guess my question was related to the feasibility of running the encoder in the browser. As you linked to, the [original demo](https://segment-anything.com/demo) only runs the decoder in the browser (inference in <50ms according to their paper), so I was wondering whether you tested running both encoder and decoder in your tests 😊

**Comment by fdwr** [comment]
*Josha*: I think if the .pth file (at 2.38GB's!) was converted to ONNX with external weights (to overcome the 2GB ProtoBuf limit), then converted to float16, then repacked with the weights back into the ONNX file (since ONNX Runtime for the web doesn't currently support external weights) that it should be possible to run with WebNN. It then becomes a matter of op coverage (I haven't collected the encoder's op list yet though ⏳).

**Comment by xenova** [comment]
Oh yikes 😅 I think we'll stick with the base and large versions:

| model| size (MB) | 8-bit quantized size (MB) |
|--------|--------|--------|
| [base](https://huggingface.co/Xenova/sam-vit-base/tree/main/onnx) | 376 | 106 |
| [large](https://huggingface.co/Xenova/sam-vit-large/tree/main/onnx) | 1250 | 330 |
| [huge](https://huggingface.co/Xenova/sam-vit-huge/tree/main/onnx) | 2560 | 664 |

**Comment by fdwr** [comment]
Indeed, the base model looks much more feasible sizewise.

**Comment by fxmarty** [comment]
@xenova a PR should be coming soon
