### ISSUE TITLE
Add IOBinding for ORTModelForVision2Seq

### ISSUE THREAD

**Issue by mht-sharma** [huggingface/optimum#1196]
### Feature request

Add IOBinding support for ORTModelForVision2Seq

### Motivation

Priority model for inference

**Comment by JingyaHuang** [comment]
Also tagging @IlyasMoutawwakil, as he tested with it yesterday!

**Comment by IlyasMoutawwakil** [comment]
@mht-sharma wile trying to solve it I found that the problem was in an output axis name that couldn't be inferred and wasn't in the in `dimensions`. It's name is `encoder_sequence_length`. As a quick patch I added it to dimensions when possible [here](https://github.com/huggingface/optimum/blob/e32ba52e4025692e1979cbbf0b4a55c02a3f2ac6/optimum/onnxruntime/modeling_ort.py#L769):
```python
if ("height" in dimensions) and ("width" in dimensions) and hasattr(self.config, "encoder"):
    dimensions["encoder_sequence_length"] = dimensions["height"] * dimensions["width"] // self.config.encoder.hidden_size
```
Not sure this is the best way to do it.
