### ISSUE TITLE
Optimisation and Quantisation for Translation models / tasks

### ISSUE THREAD

**Issue by gidzr** [huggingface/optimum#1323]
### Feature request

Currently, the opimisation and quantisation functions look for mode.onnx in a folder, and will perform opt and quant on those files. When exporting a translation targeted ONNX, multiple files for encoding and decoding, and these can't be optimised or quantised. 

I've tried a hacky approach to change names of each of these files and then applying opt and quant, and this fails. I suspect it's more than just namings.

Is it possible to optimise and quant translation ONNX files in future?

### Motivation

I would like to get smaller more efficient translation models

### Your contribution

Nothing really that I can contribute to building the solution, as I don't have that level of experience and understanding.

**Comment by IlyasMoutawwakil** [comment]
Hi, It is possible to perform optimization on translation models. 
The trick is to apply it during export from the command line: `optimum-cli export onnx --model t5-base --optimize O3`. 
That's because these models have a decoder component which is represented by two `.onnx` files and they are merged at the end of the export. Right now, optimizations can only be performed on the unmerged decoder and then it gets merged.
For quantization, the difficulty is in static quantization where calibration gets tricky because it should be performed on model components separately. But nothing is stopping you from using dynamic quantization.

**Comment by gidzr** [comment]
Awesome, thanks. Yep - been playing around this CLI.. and it's working as advertised. Very nice!
