### ISSUE TITLE
`ORTTrainer` doesn't work with distributed training and/or DeepSpeed

### ISSUE THREAD

**Issue by jambayk** [huggingface/optimum#145]
`ORTTrainer.train` fails with distributed training and/or deepspeed. 

[The line](https://github.com/jambayk/optimum/blob/dfe330a2888f3e7fd82fff73d7481faa34fe94e5/optimum/onnxruntime/trainer.py#L639) `inference_manager = model._torch_module._execution_manager._inference_manager` assumes that `model` is of type `ORTModule`. However, when deepspeed is enabled, it is of type `DeepSpeedEngine`. Its type is `DistributedDataParallel` during distributed training.

This leads to an AttributeError for such cases.

**Comment by echarlaix** [comment]
Thanks for reporting it ! Pinging @JingyaHuang

**Comment by JingyaHuang** [comment]
Hi @jambayk, 

Thanks for reporting! 

The error comes from the fact that the case of double wrappers `DeepSpeedEngine` and `ORTModule` is not yet considered in `ORTTrainer`. We are actively working on enabling distributed features in `ORTTrainer` and you can track the progress from PR #148 .

**Comment by JingyaHuang** [comment]
Hi @jambayk,

The compatibility with DeepSpeed is fixed in PR #148. There are some features currently not compatible(ZeRO stage 3/ BF16, etc.) with `ORTModule`, you can find the details about what is working and what is not in the PR. We are working on enabling more features! 

Will leave this issue open until the next release of Optimum with the fix included, please feel free to reach out if there is any question.

**Comment by jambayk** [comment]
Hi @JingyaHuang, thanks for your work on this!

**Comment by JingyaHuang** [comment]
Closing this, as DeepSpeed is enabled with the release of transformers 4.19.3. Feel free to reach out if there is any further question.
