### ISSUE TITLE
support mixtral BetterTransformer

### ISSUE THREAD

**Issue by aprilatmc** [huggingface/optimum#1609]
### Feature request

NotImplementedError: The model type mixtral is not yet supported to be used with BetterTransformer. 

### Motivation

Mixtral 8x7B is so popular these days. I believe with BetterTransformer's support on this model type, users will be using this model more in inference.

### Your contribution

No.

**Comment by fxmarty** [comment]
Hi @aprilatmc, thank you. The main feature from BetterTransformer for decoder-only models was the use of the pytorch scaled_dot_product_attention operator instead of the manual attention implementation in Transformers.

Recently, the support of SDPA has been made native in Transformers (see https://github.com/huggingface/transformers/releases/tag/v4.36.0 & https://huggingface.co/docs/transformers/main/en/perf_infer_gpu_one#pytorch-scaled-dot-product-attention & https://huggingface.co/docs/transformers/main/en/perf_infer_gpu_one#bettertransformer), so if you torch>=2.1.1 you should already benefit from SDPA speedups on supported hardware.
