### ISSUE TITLE
Support Mistral models in BetterTransformer

### ISSUE THREAD

**Issue by chunhui-shi** [huggingface/optimum#1610]
### Feature request

Mistral Models are on hugging face's hub, but are not supported in optimum yet.
When trying to load Mistral-7B-Instruct-v0.1 without a GPU on a linux machine, the following error will be triggerred.

File "/home/dev/ml/LLM-As-Chatbot/models/mistral.py", line 50, in load_model
    model = BetterTransformer.transform(model)
  File "/usr/lib/python3.10/contextlib.py", line 79, in inner
    return func(*args, **kwds)
  File "/home/cshi/dev/py/ml/lib/python3.10/site-packages/optimum/bettertransformer/transformation.py", line 234, in transform
    raise NotImplementedError(
NotImplementedError: The model type mistral is not yet supported to be used with BetterTransformer. F

### Motivation

To run Mistral models with BetterTransformer

### Your contribution

Could help with the PR

**Comment by fxmarty** [comment]
Hi @chunhui-shi, thank you. The main feature from BetterTransformer for decoder-only models was the use of the pytorch scaled_dot_product_attention operator instead of the manual attention implementation in Transformers.

Recently, the support of SDPA has been made native in Transformers (see https://github.com/huggingface/transformers/releases/tag/v4.36.0 & https://huggingface.co/docs/transformers/main/en/perf_infer_gpu_one#pytorch-scaled-dot-product-attention & https://huggingface.co/docs/transformers/main/en/perf_infer_gpu_one#bettertransformer), so if you torch>=2.1.1 you should already benefit from SDPA speedups on supported hardware.
