### ISSUE TITLE
似乎不支持cpu

### ISSUE THREAD

**Issue by andeyeluguo** [huggingface/optimum#1717]
只能支持gpu,但是官方gptq库的cpu已经支持了
[       if not torch.cuda.is_available():
            raise RuntimeError("No GPU found. A GPU is needed to quantize model.")](https://github.com/huggingface/optimum/blob/b5f4de3199a112d951c41baab5648d240df3f21c/optimum/gptq/quantizer.py#L322C8-L323C83)

**Comment by JingyaHuang** [comment]
Gently pinging @SunMarc and @fxmarty, do we have a plan on supporting gptq on CPUs?

**Comment by SunMarc** [comment]
Hi @andeyeluguo, you can't quantize a model using gptq quantization scheme without GPUs since it is not supported + it would take way too much time. However, you can run a gptq model with CPU if this is your use case ! Check the documentation [here](https://huggingface.co/docs/transformers/main/en/quantization#quantization:~:text=The%20ExLlama%20kernels%20are,Copied).
