### ISSUE TITLE
Posibility to load an ORTQuantizer or ORTOptimizer from Onnx

### ISSUE THREAD

**Issue by Ierezell** [huggingface/optimum#198]
FIrst, thanks a lot for this library, it make work so much easier. 

I was wondering if it's possible to quantize and then optimize a model (or the reverse) but looking at the doc, it seems possible to do so only by passing a huggingface vanilla model. 

Is it possible to do so with already compiled models? 

Like : MyFineTunedModel ---optimize----> MyFineTunedOnnxOptimizedModel -----quantize-----> MyFinalReallyLightModel

```python
# Note that self.model_dir is my local folder with my custom fine-tuned hugginface model
onnx_path = self.model_dir.joinpath("model.onnx")
onnx_quantized_path = self.model_dir.joinpath("quantized_model.onnx")
onnx_chad_path = self.model_dir.joinpath("chad_model.onnx")
onnx_path.unlink(missing_ok=True)
onnx_quantized_path.unlink(missing_ok=True)
onnx_chad_path.unlink(missing_ok=True)

quantizer = ORTQuantizer.from_pretrained(self.model_dir, feature="token-classification")
quantized_path = quantizer.export(
    onnx_model_path=onnx_path, onnx_quantized_model_output_path=onnx_quantized_path,
    quantization_config=AutoQuantizationConfig.arm64(is_static=False, per_channel=False),
)
quantizer.model.save_pretrained(optimized_path.parent) # To have the model config.json
quantized_path.parent.joinpath("pytorch_model.bin").unlink() # To ensure that we're not loading the vanilla pytorch model

# Load an Optimizer from an onnx path... 
# optimizer = ORTOptimizer.from_pretrained(quantized_path.parent, feature="token-classification")  <-- this fails
# optimizer.export(
#     onnx_model_path=onnx_path,
#     onnx_optimized_model_output_path=onnx_chad_path,
#     optimization_config=OptimizationConfig(optimization_level=99),
# )
model = ORTModelForTokenClassification.from_pretrained(quantized_path.parent, file_name="quantized_model.onnx")
# Ideally would load onnx_chad_path (with chad_model.onnx) if the commented section works.

tokenizer: PreTrainedTokenizer = AutoTokenizer.from_pretrained(self.model_dir)
self.pipeline = cast(TokenClassificationPipeline, pipeline(
    model=model, tokenizer=tokenizer,
    task="token-classification", accelerator="ort",
    aggregation_strategy=AggregationStrategy.SIMPLE,
    device=device_number(self.device),
))
```

Note that optimization alone works perfectly fine, quantization too, but I was hopping that both would be feasible.. unless optimization also does some kind of quantization or lighter model ?

Thanks in advance. 
Have a great day

**Comment by echarlaix** [comment]
Hi @Ierezell,

It is possible to combine optimization with quantization as when calling the `export` method of both the [optimizer](https://github.com/huggingface/optimum/blob/main/optimum/onnxruntime/optimization.py#L93) and the [quantizer](https://github.com/huggingface/optimum/blob/main/optimum/onnxruntime/quantization.py#L277) you can give an already exisiting onnx model path `onnx_model_path` (which can be already optimized or quantized for example). We are currently working on the refactorization of the `ORTOptimizer` and `ORTQuantizer` in order to simplify their usage, you can follow the progress [here](https://github.com/huggingface/optimum/tree/quantizer-decouple).
