### ISSUE TITLE
cannot import name 'cached_path' from 'transformers.file_utils'

### ISSUE THREAD

**Issue by tsaiHY** [huggingface/optimum#344]
### System Info

```shell
from optimum.onnxruntime import ORTQuantizer, ORTModelForTextClassification

then:

RuntimeError: Failed to import optimum.onnxruntime.quantization because of the following error (look up to see its traceback):
cannot import name 'cached_path' from 'transformers.file_utils'
```

### Information

- [X] The official example scripts
- [ ] My own modified scripts

### Tasks

- [X] An officially supported task in the `examples` folder (such as GLUE/SQuAD, ...)
- [ ] My own task or dataset (give details below)

### Reproduction

from optimum.onnxruntime import ORTQuantizer, ORTModelForTextClassification

### Expected behavior

this would not be fail

**Comment by tsaiHY** [comment]
transformers-4.21.1 won't fail

**Comment by nbroad1881** [comment]
I believe this will need to be patched to work for two versions of transformers: before 4.22.0 and after 4.22.0

The file utils were modified in this pull request: https://github.com/huggingface/transformers/pull/18497 and a few later ones.  

Since many functions were removed and modified in 4.22.0, I looked into which functions would need to change. Below, the left side has the names that work for < 4.22.0, and the right side has the names of the new functions that can be used for >= 4.22.0. This was only from a brief skim of the old and new code:

cached_path -> cached_file

get_list_of_files -> (no clear replacement)

hf_bucket_url/is_remote_url -> get_file_from_repo

@echarlaix @michaelbenayoun

**Comment by echarlaix** [comment]
Thanks for the detailed answer @nbroad1881 ! I opened https://github.com/huggingface/optimum/pull/368 to fix the issues you listed.

**Comment by jermwatt** [comment]
This is still an issue for me using transformers 4.31.0 - downgrading to 4.21 solved as a workaround.

**Comment by fxmarty** [comment]
Hi @jermwatt, this issue should not happen anymore: https://github.com/huggingface/optimum/blob/0b08a1fd19005b7334aa923433b3544bd2b11ff2/optimum/configuration_utils.py#L41 Which version of optimum are  you running?
