### ISSUE TITLE
Convert Seq2Seq model to ONNX while splitting encoder-decoder. 

### ISSUE THREAD

**Issue by ZiyueWangUoB** [huggingface/optimum#424]
Hi guys, I've recently been trying to convert my trained BART model to onnx. I've found that when using `transformers.onnx` from transformers, the resulting onnx file is a singular `.onnx` file. However, when using `ORTModelForSequenceClassification.from_pretrained()` and then saving the result I have three files, encoder, decoder and decoder-with-past. I want to use the pipeline provided by optimum for inference, but I am unable to convert my PyTorch trained BART model directly into the three different models.

Is there any way I could do this? Thanks.

**Comment by JingyaHuang** [comment]
Hi @ZiyueWangUoB, 
In optimum, we choose to export sequence-to-sequence models to an encoder and decoders in order to loop through (the) decoder(s) during inference. 

When `use_cache=True`, `decoder` with be used during the first iteration, and then `decoder_with_past` will be used to leverage pre-computed self-attention and cross-attention keys/values for latter iterations. That's why you have three ONNX files in the box(btw, I don't think `ORTModelForSequenceClassification` has this behavior, are you using `ORTModelForSeq2SeqLM`?).

If your bart checkpoint can be loaded with transformers, its export should be quite straightforward in Optimum with `ORTModelForSeq2SeqLM` API. Does your model have some custom layers/inputs/outputs? 

You can find more details about seq2seq inference [here](https://huggingface.co/docs/optimum/onnxruntime/usage_guides/models#export-and-inference-of-sequencetosequence-models)

**Comment by ZiyueWangUoB** [comment]
Hi @JingyaHuang,

I found my error, I was not saving the tokenizer as well so the loading was failing. Also did not have the `from_transformers=True` so it was looking for the onnx files. Thank you!
