### ISSUE TITLE
Incorrect transcription

### ISSUE THREAD

**Issue by hamsipower** [huggingface/optimum#685]
### System Info

```shell
Name: optimum
Version: 1.6.1
Google Colab
```

### Who can help?

@JingyaHuang, @echarlaix 

### Information

- [X] The official example scripts
- [ ] My own modified scripts

### Tasks

- [ ] An officially supported task in the `examples` folder (such as GLUE/SQuAD, ...)
- [ ] My own task or dataset (give details below)

### Reproduction

![resim](https://user-images.githubusercontent.com/61594743/211576411-171e1ae9-1929-4f71-80b0-12ed05c1e009.png)

### Expected behavior

The text should be longer, it's a 30 second clip with a lot of talking and the language should be Turkish. Tried running with #420 .

**Comment by fxmarty** [comment]
Hi @hamsipower , thanks for the report! Did you try with the original PyTorch model from Transformers? If the output is different it's indeed a bug, we'll have a loop asap.

**Comment by hamsipower** [comment]
![resim](https://user-images.githubusercontent.com/61594743/211640112-76747f61-bdd2-4d9a-a017-8be6e02210de.png)

@fxmarty , tried installing directly from github but no evail. :( 
Considered using an earlier version of optimum, but the ONNX support for Seq2Seq is pretty new, so...

**Comment by fxmarty** [comment]
Thank you! Could you share the collab or the code copy/pastable so that I have a look?

**Comment by hamsipower** [comment]
@fxmarty , since you added `onnxruntime` tag, I changed the onnxruntime version to `onnxruntime==1.12.0` and it seems to work on Colab. However, it still translates given audio to English.

**Comment by fxmarty** [comment]
@hamsipower Is there anything working with the vanilla pytorch pipeline that is not using an ORTModel? I'm not super familiar with ASR, but to me if you don't pass `model.config.forced_decoder_ids = processor.get_decoder_prompt_ids(language="tr", task = "transcribe")` even the PyTorch model returns garbage output (`I will explain the design` instead of `Bir toplantı yapmıştık bu anahtar kelimeleri daha iyi nasıl etc etc etc`).

I feel like the ASR pipeline doc/implementation https://huggingface.co/docs/transformers/v4.25.1/en/main_classes/pipelines#transformers.AutomaticSpeechRecognitionPipeline is lacking to specify the language and task maybe

**Comment by hamsipower** [comment]
@fxmarty , yes you're correct. That was a mistake on my part, just thought it will detect language in the pipeline similar to `whisper` library. Thank you for suggestions, got a lot of reading to do. 

I will open a new issue if the performance issue persists, thank you!

**Comment by fxmarty** [comment]
@hamsipower Yes, to run ONNX Runtime on GPU you need to install `onnxruntimeg-gpu` and not `onnxruntime` which is CPU only.

I'll close, feel free to open a new issue!
